# PLC Analyzer Configuration
app:
  name: "PLC报警系统分析器"
  version: "1.0.0"
  debug: true
  log_level: "INFO"

# DeepSeek R1 Configuration
deepseek:
  api_base: "https://api.deepseek.com"
  api_key: "sk-af5337d0cc0a4023861aa343bae4033d"
  model: "deepseek-reasoner"
  max_tokens: 32000
  temperature: 0.1
  max_concurrent_requests: 20
  request_timeout: 300
  retry_times: 3
  retry_delay: 2

# XML Processing Configuration
xml_processing:
  max_shard_lines: 1500
  min_shard_lines: 800
  overlap_lines: 100
  target_shard_count: 150
  chunk_size: 1024
  encoding: "utf-8"
  
# Parallel Processing Configuration  
parallel:
  max_workers: 20
  batch_size: 16
  queue_size: 500
  worker_timeout: 600
  result_timeout: 300
  
# Knowledge Graph Configuration
knowledge_graph:
  neo4j_uri: "bolt://localhost:7687"
  neo4j_user: "neo4j"
  neo4j_password: "${NEO4J_PASSWORD}"  # Set in environment variable
  max_connections: 50
  connection_timeout: 30
  
# Analysis Configuration
analysis:
  few_shot_examples: 5
  confidence_threshold: 0.7
  max_analysis_depth: 3
  context_window_size: 2000
  
# Cache Configuration
cache:
  redis_host: "localhost"
  redis_port: 6379
  redis_db: 0
  cache_ttl: 3600
  max_cache_size: "1GB"
  
# Monitoring Configuration
monitoring:
  metrics_port: 9090
  health_check_interval: 30
  performance_log_interval: 60
  alert_threshold:
    cpu_usage: 85
    memory_usage: 90
    error_rate: 5
    
# Web UI Configuration
web:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 4
  static_dir: "static"
  template_dir: "templates" 